name: Build and release packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build in Docker (Arch Linux)
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest bash -c "
            pacman -Syu --noconfirm && 
            pacman -S --noconfirm base-devel rust cargo-deb &&
            cargo deb &&
            echo 'Gonna do cargo arch now:' &&
            useradd -m builder &&
            su builder -c 'cargo install cargo-arch' &&
            chown -R builder:builder /workspace &&
            su builder -c 'cargo arch -f' &&
            rm *debug* &&
            echo 'depends=("gcc-libs" "glibc")' >> PKGBUILD &&
            makepkg -f
            "

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-cli-deb
          path: target/debian/*.deb

      - name: Upload .pkg.tar.zst package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-cli-arch
          path: ./*.pkg.tar.zst

      - name: Upload PKGBUILD as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-cli-pkgbuild
          path: PKGBUILD


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download .deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: pomodoro-cli-deb
          path: artifacts/

      - name: Download .pkg.tar.zst package artifact
        uses: actions/download-artifact@v4
        with:
          name: pomodoro-cli-arch
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
