name: Build and release packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build in Docker (Arch Linux)
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest bash -c "
            pacman -Syu --noconfirm && 
            pacman -S --noconfirm base-devel rust cargo-deb &&
            useradd -m builder &&
            cargo deb &&
            su builder -c 'cargo install cargo-arch' &&
            su builder -c 'cargo arch' &&
            ls &&
            rm *debug*"

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-cli-deb
          path: target/debian/*.deb

      - name: Upload .pkg.tar.zst package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-cli-arch
          path: ./*.pkg.tar.zst

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download .deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: pomodoro-cli-deb
          path: artifacts/

      - name: Download .pkg.tar.zst package artifact
        uses: actions/download-artifact@v4
        with:
          name: pomodoro-cli-arch
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
