name: Build and release packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build in Docker (Arch Linux)
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest bash -c "
          pacman -Syu --noconfirm && 
          pacman -S --noconfirm base-devel rust cargo-deb cargo-arch &&
          cargo deb &&
          cargo arch"

    - name: Upload .deb package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pomodoro-cli-deb
        path: target/debian/*.deb

    - name: Upload .pkg.tar.zst package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pomodoro-cli-arch
        path: target/arch/*.pkg.tar.zst
